remote_theme: daattali/beautiful-jekyll@6.0.1

title: "Home"
author: "Ravneet-Rahul Sandhu Singh"

timezone: "Europe/Madrid"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

###############################################
#              Navigation Bar                #
###############################################
navbar-links:
  About Me: "aboutme"

#####################################
#      Footer Social Links         #
#####################################
social-network-links:
  email: "rahulsandhu542001@gmail.com"
  github: "RahulSandhu"
  linkedin: "Ravneet-Rahul Sandhu Singh"

###########################
#     General Options    #
###########################
share-links-active:
  email: true
  github: true
  linkedin: true

url-pretty: "RahulSandhu.github.io"
title-on-all-pages: true

excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true

post_search: true
edit_page_button: true
navbar-var-length: false

date_format: "%B %-d, %Y"

######################################
#    Colors & Background Image      #
######################################
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

#############################################
#        Default YAML Values               #
#############################################
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  - scope:
      path: ""
    values:
      layout: "page"

###########################################
#      Exclude from Production Build     #
###########################################
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

#######################
#      Plugins       #
#######################
plugins:
  - jekyll-paginate
  - jekyll-sitemap
