remote_theme: daattali/beautiful-jekyll@6.0.1

title: Home
author: Ravneet-Rahul Sandhu Singh

timezone: "Europe/Madrid"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

###############################################
#              Navigation Bar                #
###############################################
navbar-links:
  About Me: "aboutme"

#####################################
#      Footer Social Links         #
#####################################
social-network-links:
  email: "rahulsandhu542001@gmail.com"
  github: "RahulSandhu"
  linkedin: "Ravneet-Rahul Sandhu Singh"

###########################
#     General Options    #
###########################
share-links-active:
  email: true
  github: true
  linkedin: true

title-on-all-pages: true

excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true

post_search: true
navbar-var-length: false

date_format: "%B %-d, %Y"

######################################
#    Colors & Background Image      #
######################################
page-col: "#FDFDFD"
text-col: "#333333"
link-col: "#0077CC"
hover-col: "#005F99"
navbar-col: "#F5F5F5"
navbar-text-col: "#222222"
navbar-border-col: "#CCCCCC"
footer-col: "#F5F5F5"
footer-text-col: "#555555"
footer-link-col: "#222222"
footer-hover-col: "#005F99"

#############################################
#        Default YAML Values               #
#############################################
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  - scope:
      path: ""
    values:
      layout: "page"

###########################################
#      Exclude from Production Build     #
###########################################
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

#######################
#      Plugins       #
#######################
plugins:
  - jekyll-paginate
  - jekyll-sitemap
